---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
library(tidyverse)
library(data.table)
library(dplyr)
library(ggridges)
library(ggplot2)
library(rvest)
library(tidyr)
library(purrr)
library(stringr)
library(visreg)
```

```{r}
df <- read.csv("LICENCIATURAS DATASET.csv")
```

```{r}
summary(df)
```

```{r}
colnames(df)
```

```{r}
str(df)
```

```{r}
ValNa <- colSums(is.na(df)) / nrow(df)
round(ValNa)
```

```{r}
ggplot(df, aes(y = EDAD)) + 
  geom_boxplot()

```

## Agrupar por Licenciatura

```{r}
ggplot(df, aes(x = CARRERA,
               fill = factor(CARRERA,
                             levels = c("1", "2", "3", "4", "5", "6", "7"),
                             labels = c("ICO", "LIA", "LAM", "LPS", "LCN", "LDE", "MACSCO")))) + 
  geom_bar()
```

## Edad por carrera

```{r}
ggplot(df, aes(x = EDAD)) + 
  geom_histogram(fill = "cornflowerblue", color = "white") + 
  facet_wrap(~CARRERA, nrow = 2)
```

## Sexo y edad

```{r}
ggplot(df, aes(x = factor(EDAD),
               fill = factor(SEXO, 
                             levels = c("1", "2"),
                             labels = c("Hombre", "Mujer")))) + 
  geom_bar(position = "dodge") + 
  coord_flip()
```

## Hombres y mujeres a favor del uso del cubrebocas

```{r}
ggplot(df, aes(x = factor(CUBREBOCAS_NECESARIO),
               fill = factor(SEXO,
#                            levels = c("1", "2"),
                             labels = c("Hombre", "Mujer")))) + 
  geom_bar(position = "dodge")
```

## Estudiantes de cada licenciatura a favor o en contra de usar cubrebocas

```{r}
ggplot(df, aes(x = factor(CUBREBOCAS_NECESARIO),
               fill = factor(CARRERA,
                             levels = c("1", "2", "3", "4", "5", "6", "7"),
                             labels = c("ICO", "LIA", "LAM", "LPS", "LCN", "LDE", "MASCO")))) + 
  geom_bar(position = "dodge")
```

Estudiantes agrupados por su zona de procedencia (Rural o Urbano) a favor o en contra del uso del cubrebocas

```{r}
ggplot(df, aes(x = factor(CUBREBOCAS_NECESARIO),
               fill = factor(ZONA_PERTENENCIA,
                             levels = c("1", "2"),
                             labels = c("Rural", "Urbano")))) + 
  geom_bar(position = "dodge")
```

## Zona de Pertenencia

```{r}
ggplot(df, aes(x = factor(ZONA_PERTENENCIA),
             #  fill = factor(ZONA_PERTENENCIA,
                #             levels = c("1", "2"),
                 #            labels = c("Rural", "Urbano")))) + 
))+
  geom_bar()
```

```{r}
ggplot(df, aes(x = factor(CUBREBOCAS_NECESARIO),
               fill = factor(CUBREBOCAS_NECESARIO,
                             levels = c("1", "2"),
                             labels = c("SI", "NO")))) + 
  geom_bar()
```

```{r}
ggplot(df, aes(x = factor(OBLIGACION_NECESIDAD),
               fill = factor(OBLIGACION_NECESIDAD,
                             levels = c("1", "2"),
                             labels = c("SI", "NO")))) + 
  geom_bar()
```

```{r}
ggplot(df, aes(x = factor(CUBREBOCAS_TRANSPORTE),
               fill = factor(CUBREBOCAS_TRANSPORTE,
                             levels = c("1", "2"),
                             labels = c("SI", "NO")))) + 
  geom_bar()
```

```{r}
ggplot(df, aes(x = factor(CUBREBOCAS_TRANSPORTE),
               fill = factor(CUBREBOCAS_TRANSPORTE,
                             levels = c("1", "2"),
                             labels = c("SI", "NO")))) + 
  geom_bar()
```

```{r}
ggplot(df, aes(x = factor(COVID_PROTEGE),
               fill = factor(COVID_PROTEGE,
                             levels = c("1", "2"),
                             labels = c("SI", "NO")))) + 
  geom_bar()
```

```{r}
ggplot(df, aes(x = factor(CASO_COVID),
               fill = factor(CASO_COVID,
                             levels = c("1", "2"),
                             labels = c("SI", "NO")))) + 
  geom_bar()
```

```{r}
ggplot(df, aes(x = factor(FACTOR_NO_USO),
               fill = factor(FACTOR_NO_USO,
                             levels = c("1", "2", "3", "4"),
                             labels = c("ESTETICA", "ECONOMICO", "CLIMA", "COMODIDAD")))) + 
  geom_bar()
```

```{r}
ggplot(df, aes(x = factor(EFECTO_ECONOMIA),
               fill = factor(EFECTO_ECONOMIA,
                             levels = c("1", "2", "3", "4"),
                             labels = c("0-25%", "26-50%", "51-75%", "76-100%")))) + 
  geom_bar()
```

```{r}
ggplot(df, aes(x = factor(VACUNA_PROTEGE),
               fill = factor(VACUNA_PROTEGE,
                             levels = c("1", "2"),
                             labels = c("Si", "No")))) + 
  geom_bar()
```

# HIPOTESIS

## 
